version: '2.3'
services:
  web:
    build: .
    ports:
      - "5283:5283"
    tmpfs:
      - /mnt/syzoj-tmp1
      - /mnt/syzoj-tmp2
      - /mnt/syzoj-bin
    volumes:
      - /root/sandbox-rootfs:/sandbox-rootfs
      - /opt/syzoj/data:/mnt/syzoj-data
    privileged: true
    networks:
      syzoj_net:
        ipv4_address: 172.16.0.2
        ipv6_address: fc00::10
    depends_on:
      - mysql

    stdin_open: true
    tty: true
  mysql:
    image: "mysql:5.6"
    networks:
      syzoj_net:
        ipv4_address: 172.16.0.3
        ipv6_address: fc00::11
    environment:
      MYSQL_ROOT_PASSWORD: "root"

networks:
  syzoj_net:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
        - subnet: fc00::/64
